import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/introduction',
        'getting-started/api-keys',
        'getting-started/endpoints',
        'getting-started/authentication',
        'getting-started/rate-limiting',
      ],
    },
    {
      type: 'category',
      label: 'Public API',
      items: [{type: 'autogenerated', dirName: 'public-api'}],
    },
    {
      type: 'category',
      label: 'Private API',
      items: [{type: 'autogenerated', dirName: 'private-api'}],
    },
    {
      type: 'category',
      label: 'WebSocket API',
      items: [{type: 'autogenerated', dirName: 'websocket'}],
    },
    {
      type: 'category',
      label: 'Reference',
      items: [{type: 'autogenerated', dirName: 'reference'}],
    },
  ],
};

export default sidebars;
